run:
  timeout: 5m
  go: '1.25'
linters:
  enable:
    - staticcheck
    - revive
    - errcheck
    - gosec
    - ineffassign
    - misspell
    - gocognit
    - dupl
    - goconst
    - unconvert
    - unparam
    - nakedret
linters-settings:
  gocognit:
    min-complexity: 15
issues:
  exclude-use-default: false
